name: github_clone
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-165.1.beta <3.0.0"

dependencies:
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  flutter:
    sdk: flutter
  #github signin in
  github_sign_in: ^0.0.5-dev.4
  get: ^4.6.5
  get_storage: ^2.0.2
  lottie: ^1.4.3
  #font awesome for icons
  font_awesome_flutter: ^10.1.0
  #responsive_framework:
  dio: ^4.0.0

  path_provider: ^2.0.1

  #Shimmer animation
  shimmer: ^2.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
